[build]
  command = "npm install --unsafe-perm && npm run build"
  publish = "build/"

  [build.environment]
    SYSTEM_VERSION = "latest"

[[plugins]]
  package = "@netlify/plugin-install-dependencies"
